name: check_words
description: "离线优先的词汇学习应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  # 状态管理
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.4.0
  
  # 璺敱
  go_router: ^13.2.4
  
  # 数据库
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # 鏈湴瀛樺偍
  shared_preferences: ^2.2.2
  
  # 缃戠粶璇锋眰
  dio: ^5.4.1
  
  # 鏁版嵁妯″瀷
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # 鍥介檯鍖?  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  
  # UI缁勪欢
  material_color_utilities: ^0.11.1
  
  # 鍥剧墖澶勭悊
  image_picker: ^1.0.7
  
  # 宸ュ叿搴?  uuid: ^4.3.3
  
  # 鍔犲瘑
  crypto: ^3.0.3

  # SQLite数据库
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

  # 音频播放
  audioplayers: ^6.0.0

  # 权限处理
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # 浠ｇ爜鐢熸垚
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  drift_dev: ^2.16.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  
  # 缁勪欢棰勮宸ュ叿
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/main.db
    - assets/data/db/
    - assets/data/json/
    - lib/l10n/arb/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: SourceHanSansSC
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Regular.otf
        - asset: assets/fonts/SourceHanSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/SourceHanSansSC-Bold.otf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: zh_CN
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated




